/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ufes.view;

import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

public class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuDados = new javax.swing.JMenu();
        jMenuItemIncluirProdutos = new javax.swing.JMenuItem();
        jMenuItemBuscarProdutos = new javax.swing.JMenuItem();
        jMenuItemCategorias = new javax.swing.JMenuItem();
        jMenuItemCalcularLucro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuDados.setText("Dados");

        jMenuItemIncluirProdutos.setText("Incluir Produtos");
        jMenuItemIncluirProdutos.addActionListener(this::jMenuItemIncluirProdutosActionPerformed);
        jMenuDados.add(jMenuItemIncluirProdutos);

        jMenuItemBuscarProdutos.setText("Buscar Produtos");
        jMenuDados.add(jMenuItemBuscarProdutos);

        jMenuItemCategorias.setText("Categorias");
        jMenuDados.add(jMenuItemCategorias);

        jMenuItemCalcularLucro.setText("Calcular Margem de Lucro");
        jMenuItemCalcularLucro.setToolTipText("");
        jMenuDados.add(jMenuItemCalcularLucro);

        jMenuBarPrincipal.add(jMenuDados);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemIncluirProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIncluirProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemIncluirProdutosActionPerformed

    public JMenuBar getjMenuBarPrincipal() {
        return jMenuBarPrincipal;
    }

    public JMenu getjMenuDados() {
        return jMenuDados;
    }

    public JMenuItem getjMenuItemBuscarProdutos() {
        return jMenuItemBuscarProdutos;
    }

    public JMenuItem getjMenuItemCalcularLucro() {
        return jMenuItemCalcularLucro;
    }

    public JMenuItem getjMenuItemCategorias() {
        return jMenuItemCategorias;
    }

    //foi necessario pesquisar qual elemento era
    public JMenuItem getjMenuItemIncluirProdutos() {
        return jMenuItemIncluirProdutos;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuDados;
    private javax.swing.JMenuItem jMenuItemBuscarProdutos;
    private javax.swing.JMenuItem jMenuItemCalcularLucro;
    private javax.swing.JMenuItem jMenuItemCategorias;
    private javax.swing.JMenuItem jMenuItemIncluirProdutos;
    // End of variables declaration//GEN-END:variables
}
